fix: tag conflict when pushing v0.3.0
> Error: fatal: Cannot fetch both <sha> and refs/tags/<tag> to refs/tags/<tag>
> — https://github.com/TACC/TACC-Docs/actions/runs/9183034344/job/25252965529

Solution from:
https://github.com/actions/checkout/issues/1467#issuecomment-1713257282